const fs = require("fs");
const os = require("os");
const path = require("path");
const request = require("supertest");
const app = require("../index");

(async () => {
  try {
    // Accept optional CLI arg for output path to make tests deterministic
    const argv = process.argv.slice(2);
    const cliOutputPath = argv[0];
    // Ensure in-process initialization (do not bind to network in tests)
    if (typeof app.startServer === "function")
      await app.startServer({ listen: false });

    const postData = {
      title: "Automated PDF Test",
      body: "This PDF was generated by an automated script to test the /export endpoint.",
    };
    const res = await request(app).post("/export").send(postData);

    console.log("Status:", res.status);
    // Use a unique temp directory to avoid collisions in concurrent runs
    const tmpRoot = os.tmpdir();
    const tmpDir = fs.mkdtempSync(path.join(tmpRoot, "aetherpress-"));
    const samplesDir = tmpDir;

    // Allow overriding output path via ENV or CLI arg to make test runs deterministic
    const envOutputPath =
      process.env.OUTPUT_PATH ||
      (process.env.OUTPUT && process.env.OUTPUT.trim());

    // Save response body if it is a PDF (content-type check)
    const ct = res.headers["content-type"] || "";
    if (ct.includes("application/pdf")) {
      const filename = "automated_export_test_inproc.pdf";
      const out =
        cliOutputPath || envOutputPath || path.join(samplesDir, filename);
      if (res.body) {
        fs.writeFileSync(out, res.body);
        console.log("Wrote PDF to", out, "size:", fs.statSync(out).size);

        // Run non-fatal validation using server/pdfQuality when available.
        try {
          const pdfQuality = require(path.resolve(
            __dirname,
            "..",
            "pdfQuality.mjs"
          ));
          // pdfQuality is ESM; attempt to call default export if present
          const check =
            pdfQuality &&
            (pdfQuality.checkPdfQuality || pdfQuality.default || pdfQuality);
          if (typeof check === "function") {
            // convert buffer to Uint8Array when needed
            const buf = fs.readFileSync(out);
            const validation = await (async () => {
              try {
                return await check(buf, { minBytesPerPage: 10000 });
              } catch (e) {
                return {
                  ok: false,
                  errors: ["validation-exception:" + e.message],
                };
              }
            })();
            console.log("PDF validation:", JSON.stringify(validation, null, 2));
            // If running in CI, fail the process on fatal validation error
            const isCI = !!(process.env.CI || process.env.GITHUB_ACTIONS);
            if (isCI && validation && validation.ok === false) {
              console.error(
                "Fatal PDF validation errors detected; failing in CI:",
                validation.errors || []
              );
              process.exit(2);
            }
          }
        } catch (e) {
          console.warn(
            "PDF validation skipped (could not load pdfQuality):",
            e.message || e
          );
        }

        // If running in CI, or if a local `server/test-artifacts` directory exists,
        // copy the artifact there so it's easy to inspect and upload from workflows.
        const isCI = !!(process.env.CI || process.env.GITHUB_ACTIONS);
        const artifactsDir = path.resolve(__dirname, "..", "test-artifacts");
        const shouldCopy =
          isCI ||
          fs.existsSync(artifactsDir) ||
          process.env.COPY_ARTIFACTS === "1";
        if (shouldCopy) {
          if (!fs.existsSync(artifactsDir))
            fs.mkdirSync(artifactsDir, { recursive: true });
          const target = path.join(artifactsDir, filename);
          try {
            fs.copyFileSync(out, target);
            console.log("Copied artifact to", target);
          } catch (e) {
            console.warn(
              "Failed to copy artifact to",
              target,
              e && e.message ? e.message : e
            );
          }
        }
      } else {
        console.warn("No body in response");
      }
    } else {
      console.log("Response content-type:", ct);
      // Save JSON body for inspection
      const out = path.join(samplesDir, "export_request_body.json");
      fs.writeFileSync(out, JSON.stringify(res.body, null, 2));
      console.log("Wrote request/response JSON to", out);
      const isCI = !!(process.env.CI || process.env.GITHUB_ACTIONS);
      if (isCI) {
        const artifactsDir = path.resolve(__dirname, "..", "test-artifacts");
        if (!fs.existsSync(artifactsDir))
          fs.mkdirSync(artifactsDir, { recursive: true });
        const target = path.join(artifactsDir, "export_request_body.json");
        fs.copyFileSync(out, target);
        console.log("Copied artifact to", target);
      }
    }
  } catch (e) {
    console.error("Error during in-process export test:", e);
  } finally {
    // Ensure any persistent browser instance is closed before exiting the script.
    try {
      if (app && typeof app.closeServices === "function") {
        // call the exported closeServices helper which avoids process.exit
        await app.closeServices("inproc-test-complete");
        console.log("Called app.closeServices()");
      } else if (app && app.browser) {
        try {
          await app.browser.close();
          console.log("Closed app.browser directly");
        } catch (e) {}
      }
    } catch (e) {
      console.warn(
        "Failed to close browser via app.closeServices():",
        e && e.message ? e.message : e
      );
    }
  }
})();
