import { describe, it, expect } from "vitest";

describe("genieService.compose()", () => {
  it("generates valid HTML from structured ebook data", async () => {
    const genieService = require("../genieService");

    const structuredData = {
      title: "Test eBook",
      pages: [
        {
          id: "ch_1",
          title: "Chapter One",
          content: "This is the content of chapter one.",
          image: {
            concept: "A serene forest clearing",
            style: "whimsical",
            tone: "peaceful",
            palette_hint: "vibrant",
            size_hint: "full-width",
          },
        },
        {
          id: "ch_2",
          title: "Chapter Two",
          content: "This is the content of chapter two.",
          image: {
            concept: "A mysterious library",
            style: "gothic",
            tone: "mysterious",
            palette_hint: "vibrant",
            size_hint: "full-width",
          },
        },
      ],
      metadata: {
        theme: "dark",
        colorPalette: "vibrant",
        fontSizeScale: 1.0,
        density: "medium",
        model: "ebook-v1",
      },
    };

    const html = await genieService.compose(structuredData);

    // Verify HTML structure
    expect(html).toBeDefined();
    expect(typeof html).toBe("string");
    expect(html).toMatch(/<!DOCTYPE html>/);
    expect(html).toMatch(/<html lang="en">/);
    expect(html).toMatch(/<\/html>/);

    // Verify cover page
    expect(html).toMatch(/Test eBook/);
    expect(html).toMatch(/Generated by Aether AI/);

    // Verify TOC
    expect(html).toMatch(/Table of Contents/);
    expect(html).toMatch(/Chapter One/);
    expect(html).toMatch(/Chapter Two/);

    // Verify content pages
    expect(html).toMatch(/This is the content of chapter one/);
    expect(html).toMatch(/This is the content of chapter two/);

    // Verify image concepts
    expect(html).toMatch(/A serene forest clearing/);
    expect(html).toMatch(/A mysterious library/);

    // Verify theme styling
    expect(html).toMatch(/#1a1a1a/); // dark theme bg
    expect(html).toMatch(/#00d4ff/); // dark theme accent

    // Verify metadata in meta tags
    expect(html).toMatch(/theme.*dark/);
    expect(html).toMatch(/colorPalette.*vibrant/);
    expect(html).toMatch(/density.*medium/);

    // Verify epilogue
    expect(html).toMatch(/End of eBook/);
    expect(html).toMatch(/Thank you for reading/);
  });

  it("handles different themes correctly", async () => {
    const genieService = require("../genieService");

    const themes = ["dark", "light", "corporate", "bold"];

    for (const theme of themes) {
      const structuredData = {
        title: `${theme} Theme Test`,
        pages: [
          {
            id: "ch_1",
            title: "Chapter",
            content: "Content",
            image: { concept: "Test concept" },
          },
        ],
        metadata: { theme, fontSizeScale: 1.0 },
      };

      const html = await genieService.compose(structuredData);

      expect(html).toContain(`<meta name="theme" content="${theme}">`);
      expect(html).toBeDefined();
      expect(html.length > 1000).toBe(true);
    }
  });

  it("handles missing optional fields gracefully", async () => {
    const genieService = require("../genieService");

    const structuredData = {
      title: "Minimal eBook",
      pages: [
        {
          id: "ch_1",
          title: "Chapter",
          content: "Content",
          // No image provided
        },
      ],
      metadata: {}, // Minimal metadata
    };

    const html = await genieService.compose(structuredData);

    expect(html).toBeDefined();
    expect(html).toContain("Minimal eBook");
    expect(html).toContain("Chapter");
    expect(html).toContain("Content");
  });

  it("throws error when pages array is missing", async () => {
    const genieService = require("../genieService");

    const invalidData = {
      title: "Invalid eBook",
      metadata: {},
      // No pages array
    };

    await expect(genieService.compose(invalidData)).rejects.toThrow(
      /requires structured data with pages array/
    );
  });

  it("respects fontSizeScale parameter", async () => {
    const genieService = require("../genieService");

    const structuredData = {
      title: "Font Scale Test",
      pages: [
        {
          id: "ch_1",
          title: "Chapter",
          content: "Content",
        },
      ],
      metadata: {
        fontSizeScale: 1.2, // Larger font
      },
    };

    const html = await genieService.compose(structuredData);

    // Verify font size is calculated: 16 * 1.2 = 19.2 -> rounds to 19
    expect(html).toMatch(/font-size: 19px/);

    // Verify header sizes are scaled: 19 * 2.4 = 45.6 (with decimals)
    expect(html).toMatch(/h1 \{ font-size: 45\.6px/);
  });

  it("handles multiple chapters and generates correct page breaks", async () => {
    const genieService = require("../genieService");

    const structuredData = {
      title: "Multi-Chapter eBook",
      pages: Array.from({ length: 5 }).map((_, i) => ({
        id: `ch_${i + 1}`,
        title: `Chapter ${i + 1}`,
        content: `Content for chapter ${i + 1}`,
      })),
      metadata: { theme: "light" },
    };

    const html = await genieService.compose(structuredData);

    // Verify all chapters are present
    for (let i = 1; i <= 5; i++) {
      expect(html).toContain(`Chapter ${i}`);
      expect(html).toContain(`Content for chapter ${i}`);
    }

    // Verify page break classes
    const pageCount = (html.match(/class="page/g) || []).length;
    // Cover + Copyright + TOC + 5 content + Epilogue = 9 pages
    expect(pageCount).toBe(9);
  });
});
