const fs = require("fs");
const path = require("path");
const request = require("supertest");
const app = require("../index");

(async () => {
  try {
    // Ensure in-process initialization (do not bind to network in tests)
    if (typeof app.startServer === "function")
      await app.startServer({ listen: false });

    const postData = {
      title: "Automated PDF Test",
      body: "This PDF was generated by an automated script to test the /export endpoint.",
    };
    const res = await request(app).post("/export").send(postData);

    console.log("Status:", res.status);
    const samplesDir = path.resolve(__dirname, "..", "samples");
    if (!fs.existsSync(samplesDir)) fs.mkdirSync(samplesDir);

    // Save response body if it is a PDF (content-type check)
    const ct = res.headers["content-type"] || "";
    if (ct.includes("application/pdf")) {
      const filename = "automated_export_test_inproc.pdf";
      const out = path.join(samplesDir, filename);
      if (res.body) {
        fs.writeFileSync(out, res.body);
        console.log("Wrote PDF to", out, "size:", fs.statSync(out).size);
      } else {
        console.warn("No body in response");
      }
    } else {
      console.log("Response content-type:", ct);
      // Save JSON body for inspection
      const out = path.join(samplesDir, "export_request_body.json");
      fs.writeFileSync(out, JSON.stringify(res.body, null, 2));
      console.log("Wrote request/response JSON to", out);
    }
  } catch (e) {
    console.error("Error during in-process export test:", e);
  }
})();
